name: Web CI

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
